apiVersion: v1
kind: Secret
metadata:
  name: docker-config
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzdWdhbWRvY2tlcjM1IiwicGFzc3dvcmQiOiJEb2NrZXIxMjMiLCJlbWFpbCI6InRhbWFuZ3N1Z2FtMDlAZ21haWwuY29tIiwiYXV0aCI6ImMzVm5ZVzFrYjJOclpYSXpOVHBFYjJOclpYSXhNak09In19fQ==
type: kubernetes.io/dockerconfigjson

